EShopping/Areas/Admin/Models/ShipperViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace EShopping.Areas.Admin.Models
{
    public class ShipperViewModel
    {
        [Required]
        public int Shipper_Id { get; set; }
        [Required]
        [Display(Name = "Comapny Name")]
        public string CompanyName { get; set; }
        [Required]
        [Display(Name = "Phone")]
        public string Phone { get; set; }
    }
}

EShopping/Areas/Admin/Controllers/ShipperController.cs
using EShopping.Areas.Admin.Models;
using EShopping.Data.Models;
using EShopping.Service.ShipperServices;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace EShopping.Areas.Admin.Controllers
{
    public class ShipperController : Controller
    {
        private IShipperService _ShiService;
        public ShipperController(IShipperService ShiService)
        {
            _ShiService = ShiService;
        }
        public ActionResult Index()
        {
            var model = _ShiService.AllShipper().
                Select(s => new ShipperViewModel
                {
                    CompanyName = s.CompanyName,
                    Phone = s.Phone,
                    Shipper_Id = s.Shipper_Id   
                });
            return View(model);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(ShipperViewModel model)
        {
            if (ModelState.IsValid)
            {
                Shipper shipper = new Shipper();
                shipper.CompanyName = model.CompanyName;
                shipper.Phone = model.Phone;
                bool res = await _ShiService.AddShipper(shipper);
                ModelState.Clear();
                return RedirectToAction("Index");
            }

            return View(model);
        }

        [HttpGet]
        public ActionResult Edit(int Id)
        {

            var shipper = _ShiService.GetShipperById(Id);

            var shipperVm = new ShipperViewModel()
            {
                Shipper_Id=shipper.Shipper_Id,
                CompanyName = shipper.CompanyName,
                Phone=shipper.Phone,
            };
            return View(shipperVm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(ShipperViewModel model)
        {
            if (ModelState.IsValid)
            {
                Shipper shipper = _ShiService.GetShipperById(model.Shipper_Id);
                shipper.CompanyName = model.CompanyName;
                shipper.Phone = model.Phone;
                bool res = await _ShiService.UpdateShipper(shipper);
                if (res)
                {
                    ModelState.Clear();
                    return RedirectToAction("Index");
                }
            }

            return View(model);
        }

        [HttpGet]
        public ActionResult Delete(int Id)
        {
            var shipper = _ShiService.GetShipperById(Id);
            ShipperViewModel svm = new ShipperViewModel()
            {
                Shipper_Id  = shipper.Shipper_Id, 
                CompanyName=shipper.CompanyName,
                Phone=shipper.Phone
            };
            return View(svm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(ShipperViewModel model)
        {
            var category = _ShiService.GetShipperById(model.Shipper_Id);
            var res = await _ShiService.Remove(category);
            return RedirectToAction("Index");

        }
    }
}

EShopping/Areas/Admin/Views/Shipper/Create.cshtml
@model EShopping.Areas.Admin.Models.ShipperViewModel

@{
    ViewBag.Title = "Create";
}

<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
    <div class="main">
        <div class="col-lg-12">
            <div class="inline">
                <div class="col-lg-6">
                    <h1>Add New Shipper</h1>
                </div>
                <div class="col-lg-6">
                    <div class="float-right">
                        <a class="btn btn-outline-dark" href="@Url.Action("Index")">Check List</a>
                    </div>
                </div>
            </div>
        </div>
        <!--Form-->
        <br>
        <div class="col-lg-12">
            @using (Html.BeginForm("Create", "Shipper", FormMethod.Post))
            {
                @Html.AntiForgeryToken()
                <div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">Add Category</label>
                        @Html.TextBoxFor(m => m.CompanyName, null, new { @class = "form-control form-mr", placeholder = "Enter Shipper Company" })
                        @Html.ValidationMessageFor(m => m.CompanyName, null, new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">Phone Number</label>
                        @Html.TextBoxFor(m => m.Phone, new { @class = "form-control form-mr", placeholder = "Enter Phone", rows = "10" })
                        @Html.ValidationMessageFor(m => m.Phone, null, new { @class = "text-danger" })
                    </div>
                    <div class="col-lg-12">
                        <input type="submit" value="Add" class="add-btn" />
                    </div>
                </div>
            }

        </div>
    </div>
</main>

EShopping/Areas/Admin/Views/Shipper/Delete.cshtml
@model EShopping.Areas.Admin.Models.ShipperViewModel

@{
    ViewBag.Title = "Delete";
}

<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
    <div class="main">
        <div class="col-lg-12">
            <div class="inline">
                <div class="col-lg-6">
                    <h1>Delete Shipper</h1>
                </div>
            </div>
        </div>
        <!--Form-->
        <br>
        <div class="col-lg-12">
            <h3>Are you sure you want to delete Shipper @Model.CompanyName ?</h3>
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                @Html.HiddenFor(m => m.Shipper_Id)

                <div class="form-actions no-color">
                    <input type="submit" value="Delete" class="btn btn-outline-danger" /> |
                    <a class="btn btn-outline-dark" href="@Url.Action("Index")">Back to List</a>
                </div>
            }
        </div>
    </div>

</main>

EShopping/Areas/Admin/Views/Shipper/Edit.cshtml
@model EShopping.Areas.Admin.Models.ShipperViewModel

@{
    ViewBag.Title = "Edit";
}

<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
    <div class="main">
        <div class="col-lg-12">
            <div class="inline">
                <div class="col-lg-6">
                    <h1>Edit Shipper</h1>
                </div>
                <div class="col-lg-6">
                    <div class="float-right">
                        <a class="btn btn-outline-dark" href="@Url.Action("Index")">Back to List</a>
                    </div>
                </div>
            </div>
        </div>
        <!--Form-->
        <br>
        <div class="col-lg-12">
            @using (Html.BeginForm("Edit", "Shipper", FormMethod.Post))
            {
                @Html.HiddenFor(m => m.Shipper_Id)
                @Html.AntiForgeryToken()
                <div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">Edit Category</label>
                        @Html.TextBoxFor(m => m.CompanyName, null, new { @class = "form-control form-mr", placeholder = "Enter Shipper Comapny" })
                        @Html.ValidationMessageFor(m => m.CompanyName, null, new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">Phone Number</label>
                        @Html.TextBoxFor(m => m.Phone, new { @class = "form-control form-mr", placeholder = "Enter Phone Number", rows = "10" })
                        @Html.ValidationMessageFor(m => m.Phone, null, new { @class = "text-danger" })
                    </div>

                    <div class="col-lg-12">
                        <input type="submit" value="Update" class="add-btn" />
                    </div>
                </div>
            }

        </div>
    </div>
</main>

EShopping/Areas/Admin/Views/Shipper/Index.cshtml
@model IEnumerable<EShopping.Areas.Admin.Models.ShipperViewModel>

@{
    ViewBag.Title = "Shipper List";
}
<!--Main Dashboard-->
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
    <div class="chartjs-size-monitor" style="position: absolute; left: 0px; top: 0px; right: 0px; bottom: 0px; overflow: hidden; pointer-events: none; visibility: hidden; z-index: -1;"><div class="chartjs-size-monitor-expand" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:1000000px;height:1000000px;left:0;top:0"></div></div><div class="chartjs-size-monitor-shrink" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:200%;height:200%;left:0; top:0"></div></div></div>
    <div class="main">
        <div class="col-lg-12">
            <div class="inline">
                <div class="col-lg-6">
                    <h1>Shipper List</h1>
                </div>
                <div class="col-lg-6">
                    <div class="float-right">
                        <a class="btn btn-outline-dark" href="@Url.Action("Create","Shipper")">Add new</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-12">
            <!--Table-->
            <div class="tbl table-responsive" id="table">
                <table id="myTable" class="table table-bordered table-hover">
                    <thead class="thead-dark">
                        <tr>
                            <th scope="col">Company Name</th>
                            <th scope="col">Contact</th>
                            <th scope="col">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td scope="row">@item.CompanyName</td>
                                <td>@item.Phone</td>
                                <td>
                                    <a class="edt-btn" href="@Url.Action("Edit","Shipper",new { Id=item.Shipper_Id})"><i class="fas fa-pencil-alt"></i></a>
                                    <a class="del-btn" href=@Url.Action("Delete","Shipper",new { Id=item.Shipper_Id})><i class="fas fa-trash"></i></a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</main>
@section scriptsAdmin{
    <script type="text/javascript">
        $(document).ready(function () {
            $('#myTable').DataTable();
        });

    </script>
}