EShopping/Areas/Admin/Models/ProductTypeViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace EShopping.Areas.Admin.Models
{
    public class ProductTypeViewModel
    {
        public int ProductType_Id { get; set; }

        [Required]
        [Display(Name = "Product type")]
        public string Name { get; set; }

        [Required]
        [Display(Name = "Product type description")]
        public string Description { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}

EShopping/Areas/Admin/Controllers/ProductTypeController.cs
using EShopping.Service.ProductTypeServices;
using System.Linq;
using System.Web.Mvc;
using EShopping.Areas.Admin.Models;
using System.Threading.Tasks;
using EShopping.Data.Models;
using System.Collections.Generic;
using EShopping.Areas.Admin.Models.AttributeViewModels;

namespace EShopping.Areas.Admin.Controllers
{
    public class ProductTypeController : Controller
    {
        private IProductTypeService _PTypeService;
        public ProductTypeController(IProductTypeService PTypeService)
        {
            _PTypeService = PTypeService;
        }
        public ActionResult Index()
        {
            var model = _PTypeService.AllProducttype().
                Select(pt => new ProductTypeViewModel
                {
                    ProductType_Id = pt.ProductType_Id,
                    Name = pt.Name,
                    Description = pt.Description,
                    Active = pt.Active
                });
            return View(model);
        }

        [HttpGet]
        public ActionResult Create()
        {
            ViewBag.Active = populateStatusCombo();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(ProductTypeViewModel model)
        {
            if (ModelState.IsValid)
            {
                ProductType pt = new ProductType();
                pt.Name= model.Name;
                pt.Description= model.Description;
                pt.Active = model.Active;
                bool res = await _PTypeService.AddP_Type(pt);
                ModelState.Clear();
                return RedirectToAction("Index");
            }
            ViewBag.Active = populateStatusCombo();
            return View(model);
        }

        [HttpGet]
        public ActionResult Edit(int Id)
        {

            var pt = _PTypeService.GetP_TypeById(Id);

            var ptViewmodel = new ProductTypeViewModel()
            {
                ProductType_Id = pt.ProductType_Id,
                Name = pt.Name,
                Description = pt.Description,
                Active = pt.Active
            };
            ViewBag.Active = populateStatusCombo();
            return View(ptViewmodel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(ProductTypeViewModel model)
        {
            if (ModelState.IsValid)
            {
                ProductType pt= _PTypeService.GetP_TypeById(model.ProductType_Id);
                pt.Name= model.Name;
                pt.Description = model.Description;
                pt.Active = model.Active;
                bool res = await _PTypeService.UpdateP_Type(pt);
                if (res)
                {
                    ModelState.Clear();
                    return RedirectToAction("Index");
                }
            }
            ViewBag.Active = populateStatusCombo();
            return View(model);
        }

        [HttpGet]
        public ActionResult Delete(int Id)
        {
            var pt = _PTypeService.GetP_TypeById(Id);
            ProductTypeViewModel model = new ProductTypeViewModel()
            {
                ProductType_Id = pt.ProductType_Id,
                Name = pt.Name
            };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(ProductTypeViewModel model)
        {
            var attribute = _PTypeService.GetP_TypeById(model.ProductType_Id);
            var res = await _PTypeService.Remove(attribute);
            return RedirectToAction("Index");

        }

        public IList<SelectListItem> populateStatusCombo()
        {
            IList<SelectListItem> StatusSelection = new List<SelectListItem>{
                 new SelectListItem {Text="Active", Value=true.ToString(),Selected=true},
                 new SelectListItem {Text="Inactive", Value=false.ToString()}
            };

            return StatusSelection;
        }
    }
}

EShopping/Areas/Admin/Views/ProductType/Create.cshtml
@model EShopping.Data.Models.ProductType

@{
    ViewBag.Title = "Create";
}

<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
    <div class="main">
        <div class="col-lg-12">
            <div class="inline">
                <div class="col-lg-6">
                    <h1>Add Product Type</h1>
                </div>
                <div class="col-lg-6">
                    <div class="float-right">
                        <a class="btn btn-outline-dark" href="@Url.Action("Index")">Check List</a>
                    </div>
                </div>
            </div>
        </div>
        <!--Form-->
        <br>
        <div class="col-lg-12">
            @using (Html.BeginForm("Create", "ProductType", FormMethod.Post))
            {
                @Html.AntiForgeryToken()
                <div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">Product Type</label>
                        @Html.TextBoxFor(m => m.Name, null, new { @class = "form-control form-mr", placeholder = "Enter Product Type eg: Shirts, Paints, Shoes" })
                        @Html.ValidationMessageFor(m => m.Name, null, new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">Description</label>
                        @Html.TextAreaFor(m => m.Description, new { @class = "form-control form-mr", placeholder = "Enter Description",rows="10"})
                        @Html.ValidationMessageFor(m => m.Description, null, new { @class = "text-danger" })
                    </div>
                   <div class="form-group">
                        @Html.DisplayNameFor(m => m.Active)
                        @Html.DropDownListFor(m => m.Active, ViewBag.Active as SelectList, new { @class = "form-control form-mr" })
                    </div>
                    <div class="col-lg-12">
                        <input type="submit" value="Add" class="add-btn" />
                    </div>
                </div>
            }

        </div>
    </div>
</main>

EShopping/Areas/Admin/Views/ProductType/Delete.cshtml
@model EShopping.Areas.Admin.Models.ProductTypeViewModel

@{
    ViewBag.Title = "Delete";
}

<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
    <div class="main">
        <div class="col-lg-12">
            <div class="inline">
                <div class="col-lg-6">
                    <h1>Delete Product Type</h1>
                </div>
            </div>
        </div>
        <!--Form-->
        <br>
        <div class="col-lg-12">
            <h3>Are you sure you want to delete Product Type @Model.Name?</h3>
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                @Html.HiddenFor(m => m.ProductType_Id)

                <div class="form-actions no-color">
                    <input type="submit" value="Delete" class="btn btn-outline-danger" /> |
                    <a class="btn btn-outline-dark" href="@Url.Action("Index")">Back to List</a>
                </div>
            }
        </div>
    </div>

</main>

EShopping/Areas/Admin/Views/ProductType/Edit.cshtml
@model EShopping.Areas.Admin.Models.ProductTypeViewModel

@{
    ViewBag.Title = "Edit";
}

<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
    <div class="main">
        <div class="col-lg-12">
            <div class="inline">
                <div class="col-lg-6">
                    <h1>Edit Product Type</h1>
                </div>
                <div class="col-lg-6">
                    <div class="float-right">
                        <a class="btn btn-outline-dark" href="@Url.Action("Index")">Check List</a>
                    </div>
                </div>
            </div>
        </div>
        <!--Form-->
        <br>
        <div class="col-lg-12">
            @using (Html.BeginForm("Edit", "ProductType", FormMethod.Post))
            {
                @Html.AntiForgeryToken()
                @Html.HiddenFor(m=>m.ProductType_Id)
                <div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">Product Type</label>
                        @Html.TextBoxFor(m => m.Name, null, new { @class = "form-control form-mr", placeholder = "Enter Product Type eg: Shirts, Paints, Shoes" })
                        @Html.ValidationMessageFor(m => m.Name, null, new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">Description</label>
                        @Html.TextAreaFor(m => m.Description, new { @class = "form-control form-mr", placeholder = "Enter Description", rows = "10" })
                        @Html.ValidationMessageFor(m => m.Description, null, new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        @Html.DisplayNameFor(m => m.Active)
                        @Html.DropDownListFor(m => m.Active, ViewBag.Active as SelectList, new { @class = "form-control form-mr" })
                    </div>
                    <div class="col-lg-12">
                        <input type="submit" value="Update" class="add-btn" />
                    </div>
                </div>
            }

        </div>
    </div>
</main>

EShopping/Areas/Admin/Views/ProductType/Index.cshtml
@model IEnumerable<EShopping.Areas.Admin.Models.ProductTypeViewModel>

@{
    ViewBag.Title = "Product type list";
}
<!--Main Dashboard-->
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
    <div class="chartjs-size-monitor" style="position: absolute; left: 0px; top: 0px; right: 0px; bottom: 0px; overflow: hidden; pointer-events: none; visibility: hidden; z-index: -1;"><div class="chartjs-size-monitor-expand" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:1000000px;height:1000000px;left:0;top:0"></div></div><div class="chartjs-size-monitor-shrink" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:200%;height:200%;left:0; top:0"></div></div></div>
    <div class="main">
        <div class="col-lg-12">
            <div class="inline">
                <div class="col-lg-6">
                    <h1>Product Type List</h1>
                </div>
                <div class="col-lg-6">
                    <div class="float-right">
                        <a class="btn btn-outline-dark" href="@Url.Action("Create","ProductType")">Add new</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-12">
            <!--Table-->
            <div class="tbl table-responsive" id="table">
                <table id="myTable" class="table table-bordered table-hover">
                    <thead class="thead-dark">
                        <tr>
                            <th scope="col">Name</th>
                            <th scope="col">Description</th>
                            <th scope="col">Status</th>
                            <th scope="col">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td scope="row">@item.Name</td>
                                <td>@item.Description</td>
                                <td>@(Convert.ToBoolean(item.Active) ? "Active" : "Inactive")</td>
                                <td>
                                    <a class="edt-btn" href="@Url.Action("Edit","ProductType",new { Id=item.ProductType_Id})"><i class="fas fa-pencil-alt"></i></a>
                                    <a class="del-btn" href="@Url.Action("Delete","ProductType",new { Id=item.ProductType_Id})"><i class="fas fa-trash"></i></a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
</main>
@section scriptsAdmin{
    <script type="text/javascript">
        $(document).ready(function () {
            $('#myTable').DataTable();
        });

    </script>
}