EShopping/Areas/Admin/Controllers/BrandController.cs
using EShopping.Areas.Admin.Models;
using EShopping.Data.Models;
using EShopping.Service.BrandServices;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace EShopping.Areas.Admin.Controllers
{
    public class BrandController : Controller
    {
        private IBrandService _BrandService;

        public BrandController(IBrandService BrandService)
        {
            _BrandService = BrandService;
        }
        public ActionResult Index()
        {
            var model = _BrandService.AllBrands().
                Select(b => new BrandViewModel
                {
                    Brand_Id=b.Brand_Id,
                    BrandName = b.BrandName,
                    Description = b.Description,
                    LogoUrl = b.Logo,
                    Active = b.Active
                });
            return View(model);
        }

        [HttpGet]
        public ActionResult Create()
        {
            ViewBag.Active = populateStatusCombo();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(BrandViewModel model)
        {
            if (ModelState.IsValid)
            {
                Brand brand = new Brand();
                if (model.BrandLogo != null && model.BrandLogo.ContentLength != 0)
                {
                    string filename = Path.GetFileNameWithoutExtension(model.BrandLogo.FileName);
                    string extension = Path.GetExtension(model.BrandLogo.FileName);
                    filename = filename + DateTime.Now.ToString("yymmssfff") + extension;
                    brand.Logo = "~/Images/BrandLogo/" + filename;
                    filename = Path.Combine(Server.MapPath("~/Images/BrandLogo/"), filename);
                    model.BrandLogo.SaveAs(filename);
                }
                else
                {
                    brand.Logo = model.LogoUrl;
                }
              
                brand.BrandName = model.BrandName;
                brand.Description = model.Description;
                brand.Active = model.Active;
                bool res = await _BrandService.AddBrand(brand);
                ModelState.Clear();
                return RedirectToAction("Index");
            }

            ViewBag.Active = populateStatusCombo();
            return View(model);
        }

        [HttpGet]
        public ActionResult Edit(int Id)
        {

            var brand = _BrandService.GetBrandById(Id);

            var brandVm = new BrandViewModel()
            {
                Brand_Id = brand.Brand_Id,
                BrandName = brand.BrandName,
                Description = brand.Description,
                LogoUrl = brand.Logo,
                Active = Convert.ToBoolean(brand.Active),
            };
            ViewBag.Active = populateStatusCombo();
            return View(brandVm);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(BrandViewModel model)
        {
            if (ModelState.IsValid)
            {
                Brand brand = _BrandService.GetBrandById(model.Brand_Id);

                if (model.BrandLogo != null && model.BrandLogo.ContentLength != 0)
                {
                    System.IO.File.Delete(Server.MapPath(model.LogoUrl));
                    string filename = Path.GetFileNameWithoutExtension(model.BrandLogo.FileName);
                    string extension = Path.GetExtension(model.BrandLogo.FileName);
                    filename = filename + DateTime.Now.ToString("yymmssfff") + extension;
                    brand.Logo = "~/Images/BrandLogo/" + filename;
                    filename = Path.Combine(Server.MapPath("~/Images/BrandLogo/"), filename);
                    model.BrandLogo.SaveAs(filename);
                }
                else
                {
                    brand.Logo = model.LogoUrl;
                }

                brand.BrandName = model.BrandName;
                brand.Description = model.Description;
                brand.Active = model.Active;
                bool res = await _BrandService.UpdateBrand(brand);
                if (res)
                {
                    ModelState.Clear();
                    return RedirectToAction("Index");
                }
            }

            ViewBag.Active = populateStatusCombo();
            return View(model);
        }

        [HttpGet]
        public ActionResult Delete(int Id)
        {
            var category = _BrandService.GetBrandById(Id);
            BrandViewModel cvm = new BrandViewModel()
            {
                Brand_Id = category.Brand_Id,
                BrandName = category.BrandName ,
                LogoUrl = category.Logo
            };
            return View(cvm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(BrandViewModel model)
        {
            var category = _BrandService.GetBrandById(model.Brand_Id );
            var res = await _BrandService .Remove(category);
            if (res && model.LogoUrl != "~/Images/default.png")
            {
                System.IO.File.Delete(Server.MapPath(model.LogoUrl));
                ModelState.Clear();
            }
            return RedirectToAction("Index");

        }

        public IList<SelectListItem> populateStatusCombo()
        {
            IList<SelectListItem> StatusSelection = new List<SelectListItem>{
                 new SelectListItem {Text="Active", Value=true.ToString(),Selected=true},
                 new SelectListItem {Text="Inactive", Value=false.ToString()}
            };

            return StatusSelection;
        }
    }
}

EShopping/Areas/Admin/Controllers/FAQController.cs
using EShopping.Areas.Admin.Models;
using EShopping.Data.Models;
using EShopping.Service.FAQService;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace EShopping.Areas.Admin.Controllers
{
    public class FAQController : Controller
    {
        private IFAQService _FAQService;
        public FAQController(IFAQService FAQService)
        {
            _FAQService = FAQService;
        }

        public ActionResult Index()
        {
            var model = _FAQService.AllFAQ().
                Select(f => new FAQViewModel{
                    FAQ_Id = f.FAQ_Id,
                    Question = f.Question,
                    Answer = f.Answer
            });
            return View(model);
        }
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(FAQViewModel model)
        {
            if (ModelState.IsValid)
            {
                FAQ faq = new FAQ();
                faq.Question= model.Question;
                faq.Answer = model.Answer;
                bool res = await _FAQService.AddFAQ(faq);
                ModelState.Clear();
                return RedirectToAction("Index");
            }

            return View(model);
        }

        [HttpGet]
        public ActionResult Edit(int Id)
        {

            var faq = _FAQService.GetFAQById(Id);

            var faqVM= new FAQViewModel()
            {
                FAQ_Id= faq.FAQ_Id,
                Question = faq.Question,
                Answer = faq.Answer,
            };
            return View(faqVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(FAQViewModel model)
        {
            if (ModelState.IsValid)
            {
                FAQ faq= _FAQService.GetFAQById(model.FAQ_Id);
                faq.Question= model.Question;
                faq.Answer= model.Answer;
                bool res = await _FAQService.UpdateFAQ(faq);
                if (res)
                {
                    ModelState.Clear();
                    return RedirectToAction("Index");
                }
            }

            return View(model);
        }

        [HttpGet]
        public ActionResult Delete(int Id)
        {
            var faq = _FAQService.GetFAQById(Id);
            FAQViewModel faqVM = new FAQViewModel()
            {
                FAQ_Id = faq.FAQ_Id, 
                Question = faq.Question
            };
            return View(faqVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(FAQViewModel model)
        {
            var category = _FAQService.GetFAQById(model.FAQ_Id);
            var res = await _FAQService.Remove(category);
            return RedirectToAction("Index");

        }

    }
}

EShopping/Areas/Admin/Controllers/OrderController.cs
using EShopping.Areas.Admin.Models;
using EShopping.Service.OrderService;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace EShopping.Areas.Admin.Controllers
{
    public class OrderController : Controller
    {
        private IOrderService _OrdService;

        public OrderController(IOrderService OrdService)
        {
            _OrdService = OrdService;
        }
        public ActionResult Index()
        {
            var model = _OrdService.AllOrders().
                Select(o => new OrderViewModel
                {
                    BillingAddress_Id = o.BillingAddress_Id,
                    Customer_Id = o.Customer_Id,
                    Discount = o.Discount,
                    NetAmount = o.NetAmount,
                    OrderAmount = o.OrderAmount,
                    OrderDate = o.OrderDate,
                    OrderStatus_Id = o.OrderStatus_Id,
                    Order_Id = o.Order_Id,
                    Payment_Id = o.Payment_Id,
                    ShipDate = o.ShipDate,
                    Shipper_Id = o.Shipper_Id,
                    ShippingAddress_Id = o.ShippingAddress_Id,
                    ShippingAmount = o.ShippingAmount,
                    ShippingDate = o.ShippingDate,
                    TaxAmount = o.TaxAmount
                });
            return View(model);
        }
    }
}

EShopping/Areas/Admin/Controllers/ProductController.cs
using EShopping.Areas.Admin.Models;
using EShopping.Areas.Admin.Models.AttributeViewModels;
using EShopping.Areas.Admin.Models.ProductViewModel;
using EShopping.Areas.Admin.Models.ProductViewModels;
using EShopping.Data.Models;
using EShopping.Service.AttributeService;
using EShopping.Service.BrandServices;
using EShopping.Service.CategoryServices;
using EShopping.Service.ProductService;
using EShopping.Service.ProductTypeServices;
using EShopping.Service.SupplierServices;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace EShopping.Areas.Admin.Controllers
{
    public class ProductController : Controller
    {
        private IProductService _ProService;
        private ISupplierService _SuppService;
        private IBrandService _BrandService;
        private ICategoryService _CatService;
        private IProductTypeService _PtService;
        private IAttributeService _attService;

        public ProductController
            (
                IProductService ProService,
                ISupplierService SuppService,
                IBrandService BrandService,
                ICategoryService CatService,
                IProductTypeService PtService,
                IAttributeService attService
             )
        {
            _ProService = ProService;
            _SuppService = SuppService;
            _BrandService = BrandService;
            _CatService = CatService;
            _PtService = PtService;
            _attService = attService;
        }
        public ActionResult Index()
        {
            var model = _ProService.AllProducts().
                Select(p => new ProductIndexViewModel
                {
                    Active = p.Active,
                    Description = p.Description,
                    ImageUrl = p.ImageUrl,
                    IsFeatured = Convert.ToBoolean(p.IsFeatured),
                    Name = p.Name,
                    Product_Id = p.Product_Id,

                });
            return View(model);
        }

        public ActionResult Create() {
            ProductCreateViewModel model = new ProductCreateViewModel();
            model = populateDropdown(model);
            ViewBag.Active = populateStatusCombo();
            return View(model);
        }
        public ActionResult Attribute(int Id) {
            IList<AttributeSelectViewModel> attributeSelectList = _attService.AttributeByProductType(Id).
                Select(m=>new AttributeSelectViewModel {
                    AttributeId=m.Attribute_Id,
                    AttributeValue="",
                }).ToList();
            ViewBag.AttributeDropDown = _attService.AttributeByProductType(Id).ToList();
            ProductCreateViewModel attributeListModel = new ProductCreateViewModel();
            attributeListModel.AttributeValueList = attributeSelectList;
            return PartialView("_Attr", attributeListModel);
        }

        public ActionResult AddProductVariation(ProductCreateViewModel model) {
            ViewBag.SelectedAttr = model.AttributeValueList.Count;
            return PartialView("AddProductVariation", model);
        }
       
        private ProductCreateViewModel populateDropdown(ProductCreateViewModel model) {
            model.BrandList = _BrandService.AllActiveBrands().Select(b=>new BrandViewModel
            {
                Brand_Id=b.Brand_Id,
                BrandName=b.BrandName
            }).ToList();

            model.SupplierList = _SuppService.AllSuppliers().Select(s => new SupplierViewModel
            {
                Supplier_Id = s.Supplier_Id,
                CompanyName = s.CompanyName
            }).ToList();

            model.CategoryList= _CatService.GetActiveCategory().Select(c => new CategoryViewModel
            {
                Category_Id = c.Category_Id,
                Name = c.Name
            }).ToList();

            model.ProductTypeList = _PtService.GetActiveProdictTypes().Select(pt => new ProductTypeViewModel
            {
                ProductType_Id = pt.ProductType_Id,
                Name = pt.Name
            }).ToList();

            return model;
        }
        public IList<SelectListItem> populateStatusCombo()
        {
            IList<SelectListItem> StatusSelection = new List<SelectListItem>{
                 new SelectListItem {Text="Active", Value=true.ToString(),Selected=true},
                 new SelectListItem {Text="Inactive", Value=false.ToString()}
            };

            return StatusSelection;
        }

        public JsonResult getAttributeValues(int attributeId) {
            var attributevalueList = _attService.getValuesByAttributeId(attributeId)
                .Select(m=>new AttributeValueViewModel {
                    AttributeValue_Id=m.AttributeValue_Id,
                    Attribute_Id=m.Attribute_Id,
                    Value=m.Value
                }).ToList();
            return Json(attributevalueList,JsonRequestBehavior.AllowGet);
        }
    }
}

EShopping/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>@ViewBag.Title</title>
    <!--Main Css-->
    <link href="~/Areas/Admin/AdminContent/css/style.css" rel="stylesheet" />
    <!--Bootstrap Css-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!--font awesome-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.0/css/all.css" integrity="sha384-Mmxa0mLqhmOeaE8vgOSbKacftZcsNYDjQzuCOm6D02luYSzBG8vpaOykv9lFQ51Y" crossorigin="anonymous">
    <!--Data Table-->
    <link rel="stylesheet" href="//cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
    @RenderSection("stylesAdmin",required: false)

</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <!--Navbar-->
                <nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-1 shadow">
                    <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">Company name</a>
                    <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
                    <ul class="navbar-nav px-3">
                        <li class="nav-item text-nowrap">
                            <a class="nav-link" href="#">Sign out</a>
                        </li>
                    </ul>
                </nav>
                <!--Aside Menu-->
                <div class="m">
                    <div class="container-fluid">
                        <div class="row">
                            <!--Aside-->
                            <nav class="col-md-2 d-none d-md-block bg-light sidebar">
                                <div class="sidebar-sticky">
                                    <ul class="nav flex-column">
                                        <li class="nav-item">
                                            <a class="nav-link active" href="@Url.Action("Index","Dashboard")">
                                                <i class="fas fa-home"></i>
                                                Dashboard <span class="sr-only">(current)</span>
                                            </a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" href="@Url.Action("Index","Attribute")">
                                                <i class="fas fa-passport"></i>
                                                Attribute
                                            </a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" href="@Url.Action("Index","Brand")">
                                                <i class="fas fa-shopping-cart"></i>
                                                Brand
                                            </a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" href="@Url.Action("Index","Customer")">
                                                <i class="fas fa-users"></i>
                                                Customers
                                            </a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" href="Reports.html">
                                                <i class="far fa-chart-bar"></i>
                                                Reports
                                            </a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" href="@Url.Action("Index","Categories")">
                                                <i class="fas fa-cubes"></i>
                                                Category
                                            </a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" href="@Url.Action("Index","FAQ")">
                                                <i class="fas fa-question"></i>
                                                FAQ
                                            </a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" href="@Url.Action("Index","Order")">
                                                <i class="fas fa-file-signature"></i>
                                                Order
                                            </a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" href="Payment.html">
                                                <i class="fas fa-credit-card"></i>
                                                Payment
                                            </a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" href="@Url.Action("Index","Product")">
                                                <i class="fas fa-boxes"></i>
                                                Product
                                            </a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" href="@Url.Action("Index","ProductType")">
                                                <i class="fas fa-box"></i>
                                                Product Type
                                            </a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" href="@Url.Action("Index","Shipper")">
                                                <i class="fas fa-dolly"></i>
                                                Shipper
                                            </a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" href="@Url.Action("Index","Supplier")">
                                                <i class="fas fa-parachute-box"></i>
                                                Supplier
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </nav>
                            <!--Main Dashboard-->
                            @RenderBody()
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!--Jquery-->
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
     
    <script src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <!--Bootstarp Js-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    
    @RenderSection("scriptsAdmin", required: false)
    <!--Main Js-->
    <script src="~/Areas/Admin/AdminContent/js/script.js"></script>
    
</body>
</html>